### ISSUE TITLE
install_github('stephens999/ash') and variations on this theme all fail

### ISSUE THREAD

**Issue by ttriche** [stephens999/ash#31]
'ashr' repo created and repo transfer initiated.  Youse guise will have to accept for it to succeed, but after that it's all yours.  Should make testing, CI, coverage estimation, etc. a lot easier if there's just one focal point for development, if in fact that's what you want.  Otherwise feel free to delete the new repo.

best,

--t

**Comment by stephens999** [comment]
This worked for me:
install_github("stephens999/ash", ref = "master", subdir = "package/ashr")
Downloading github repo stephens999/ash@master
Installing ashr
Installing dependencies for ashr:
pscl
trying URL 'http://cran.rstudio.com/bin/macosx/mavericks/contrib/3.1/pscl_1.4.8.tgz'
Content type 'application/x-gzip' length 3186140 bytes (3.0 Mb)
opened URL
==================================================
downloaded 3.0 Mb


The downloaded binary packages are in
	/var/folders/1f/d96lz9ts15g81dqs_hcc_9cr0000gq/T//RtmpzbVHaH/downloaded_packages
'/Library/Frameworks/R.framework/Resources/bin/R' --vanilla CMD INSTALL  \
  '/private/var/folders/1f/d96lz9ts15g81dqs_hcc_9cr0000gq/T/RtmpzbVHaH/devtools184d52d7b15ea/stephens999-ash-ec1ba8d/package/ashr'  \
  --library='/Library/Frameworks/R.framework/Versions/3.1/Resources/library'  \
  --install-tests 

* installing *source* package ‘ashr’ ...
** libs
make: Nothing to be done for `all'.
installing to /Library/Frameworks/R.framework/Versions/3.1/Resources/library/ashr/libs
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (ashr)

**Comment by ttriche** [comment]
This appears to only work for the Mac binary package. 

```
R> library(devtools)

Attaching package: 'devtools'

The following object is masked _by_ '.GlobalEnv':

    inst

R> install_github("stephens999/ash", ref = "master", subdir = "package/ashr")
Downloading github repo stephens999/ash@master
Installing ashr
'/usr/lib/R/bin/R' --vanilla CMD INSTALL  \
  '/tmp/RtmpoPvzvp/devtools63da4e809476/stephens999-ash-ec1ba8d/package/ashr'  \
  --library='/home/tim/R/x86_64-pc-linux-gnu-library/3.1' --install-tests 

* installing *source* package ‘ashr’ ...
** libs
make: Nothing to be done for `all'.
installing to /home/tim/R/x86_64-pc-linux-gnu-library/3.1/ashr/libs
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/tim/R/x86_64-pc-linux-gnu-library/3.1/ashr/libs/ashr.so':
  /home/tim/R/x86_64-pc-linux-gnu-library/3.1/ashr/libs/ashr.so: invalid ELF header
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/tim/R/x86_64-pc-linux-gnu-library/3.1/ashr’
* restoring previous ‘/home/tim/R/x86_64-pc-linux-gnu-library/3.1/ashr’
Error: Command failed (1)
In addition: Warning message:
In req$status : partial match of 'status' to 'status_code'
R> devtools::session_info()
Session info -------------------------------------------------------------------
 setting  value                       
 version  R version 3.1.2 (2014-10-31)
 system   x86_64, linux-gnu           
 ui       X11                         
 language en_US                       
 collate  en_US.UTF-8                 
 tz       <NA>                        

Packages -----------------------------------------------------------------------
 package                           * version    date      
 AnnotationDbi                       1.28.1     2015-01-24
 assertthat                        * 0.1        2013-12-06
 base64enc                         * 0.1-2      2014-06-26
 BatchJobs                         * 1.5        2014-10-30
 BBmisc                            * 1.9        2015-02-03
 bigrquery                           0.1        2015-01-03
 Biobase                             2.26.0     2015-01-02
 BiocGenerics                        0.12.1     2015-01-02
 BiocInstaller                       1.16.1     2015-01-02
 BiocParallel                      * 1.1.13     2015-01-30
 biomaRt                           * 2.23.5     2015-01-23
 Biostrings                        * 2.34.1     2015-01-03
 bitops                            * 1.0-6      2013-08-17
 brew                              * 1.0-6      2011-04-13
 checkmate                         * 1.5.1      2014-12-14
 codetools                         * 0.2-10     2015-01-17
 DBI                                 0.3.1      2014-09-24
 devtools                            1.7.0.9000 2015-02-09
 digest                            * 0.6.8      2014-12-31
 dplyr                             * 0.4.1      2015-01-14
 fail                              * 1.2        2013-09-19
 foreach                           * 1.4.2      2014-04-11
 GenomeInfoDb                        1.3.12     2015-01-04
 GenomicAlignments                 * 1.2.1      2015-01-03
 GenomicFeatures                     1.18.3     2015-01-24
 GenomicRanges                       1.18.4     2015-01-30
 GO.db                               3.0.0      2015-01-15
 graph                             * 1.44.1     2015-01-04
 gtools                              3.4.1      2014-05-28
 Homo.sapiens                        1.1.2      2015-01-15
 httr                              * 0.6.1      2015-01-01
 IRanges                             2.0.1      2015-01-30
 iterators                         * 1.0.7      2014-04-11
 magrittr                            1.5        2014-11-22
 OrganismDbi                         1.8.0      2015-01-15
 org.Hs.eg.db                        3.0.0      2015-01-03
 RBGL                              * 1.42.0     2015-01-15
 Rcpp                              * 0.11.4     2015-01-24
 RCurl                             * 1.95-4.5   2014-12-28
 Rsamtools                         * 1.18.2     2015-01-15
 RSQLite                             1.0.0      2014-10-25
 rstudioapi                        * 0.2        2014-12-31
 rtracklayer                       * 1.26.2     2015-01-03
 S4Vectors                           0.4.0      2015-01-30
 sendmailR                         * 1.2-1      2014-09-21
 stringr                           * 0.6.2      2012-12-06
 TxDb.Hsapiens.UCSC.hg19.knownGene   3.0.0      2015-01-24
 XML                               * 3.98-1.1   2013-06-20
 XVector                           * 0.6.0      2015-01-03
 zlibbioc                          * 1.12.0     2015-01-03
```

**Comment by stephens999** [comment]
looks to me that the problem was that the .o files were also committed, so the make command failed make: Nothing to be done for `all'.
I removed the .o files. can you try again?

**Comment by stephens999** [comment]
this now worked for me on my linux cluster
> install_github("stephens999/ash", ref = "master", subdir = "package/ashr")
Downloading github repo stephens999/ash@master
Installing ashr
Installing dependencies for ashr:
truncnorm, SQUAREM
Installing packages into ‘/mnt/lustre/home/mstephens/R/x86_64-unknown-linux-gnu-library/3.1’
(as ‘lib’ is unspecified)
trying URL 'http://cran.rstudio.com/src/contrib/truncnorm_1.0-7.tar.gz'
Content type 'application/x-gzip' length 9909 bytes
opened URL
==================================================
downloaded 9909 bytes

trying URL 'http://cran.rstudio.com/src/contrib/SQUAREM_2014.8-1.tar.gz'
Content type 'application/x-gzip' length 124167 bytes (121 Kb)
opened URL
==================================================
downloaded 121 Kb

* installing *source* package ‘truncnorm’ ...
** package ‘truncnorm’ successfully unpacked and MD5 sums checked
** libs
gcc -std=gnu99 -I/data/tools/R-3.1.1/lib64/R/include -DNDEBUG  -I/usr/local/include    -fpic  -g -O2  -c rtruncnorm.c -o rtruncnorm.o
gcc -std=gnu99 -I/data/tools/R-3.1.1/lib64/R/include -DNDEBUG  -I/usr/local/include    -fpic  -g -O2  -c truncnorm.c -o truncnorm.o
gcc -std=gnu99 -I/data/tools/R-3.1.1/lib64/R/include -DNDEBUG  -I/usr/local/include    -fpic  -g -O2  -c zeroin.c -o zeroin.o
gcc -std=gnu99 -shared -L/usr/local/lib64 -o truncnorm.so rtruncnorm.o truncnorm.o zeroin.o -L/data/tools/R-3.1.1/lib64/R/lib -lR
installing to /mnt/lustre/home/mstephens/R/x86_64-unknown-linux-gnu-library/3.1/truncnorm/libs
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (truncnorm)
* installing *source* package ‘SQUAREM’ ...
** package ‘SQUAREM’ successfully unpacked and MD5 sums checked
** R
** demo
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (SQUAREM)

The downloaded source packages are in
	‘/tmp/Rtmp5UwhMb/downloaded_packages’
'/data/tools/R-3.1.1/lib64/R/bin/R' --vanilla CMD INSTALL  \
  '/tmp/Rtmp5UwhMb/devtools6f1632af1da8/stephens999-ash-d0dea72/package/ashr'  \
  --library='/mnt/lustre/home/mstephens/R/x86_64-unknown-linux-gnu-library/3.1'  \
  --install-tests 

* installing *source* package ‘ashr’ ...
** libs
g++ -I/data/tools/R-3.1.1/lib64/R/include -DNDEBUG  -I/usr/local/include -I"/mnt/lustre/data/tools/R-3.1.1/lib64/R/library/Rcpp/include"   -fpic  -g -O2  -c MixEM.cpp -o MixEM.o
/mnt/lustre/data/tools/R-3.1.1/lib64/R/library/Rcpp/include/Rcpp/Date.h: In member function ‘void Rcpp::Date::update_tm()’:
/mnt/lustre/data/tools/R-3.1.1/lib64/R/library/Rcpp/include/Rcpp/Date.h:108: warning: converting to ‘time_t’ from ‘double’
/mnt/lustre/data/tools/R-3.1.1/lib64/R/library/Rcpp/include/Rcpp/Date.h: In function ‘Rcpp::Date Rcpp::operator+(const Rcpp::Date&, int)’:
/mnt/lustre/data/tools/R-3.1.1/lib64/R/library/Rcpp/include/Rcpp/Date.h:139: warning: converting to ‘time_t’ from ‘double’
g++ -I/data/tools/R-3.1.1/lib64/R/include -DNDEBUG  -I/usr/local/include -I"/mnt/lustre/data/tools/R-3.1.1/lib64/R/library/Rcpp/include"   -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
/mnt/lustre/data/tools/R-3.1.1/lib64/R/library/Rcpp/include/Rcpp/Date.h: In member function ‘void Rcpp::Date::update_tm()’:
/mnt/lustre/data/tools/R-3.1.1/lib64/R/library/Rcpp/include/Rcpp/Date.h:108: warning: converting to ‘time_t’ from ‘double’
/mnt/lustre/data/tools/R-3.1.1/lib64/R/library/Rcpp/include/Rcpp/Date.h: In function ‘Rcpp::Date Rcpp::operator+(const Rcpp::Date&, int)’:
/mnt/lustre/data/tools/R-3.1.1/lib64/R/library/Rcpp/include/Rcpp/Date.h:139: warning: converting to ‘time_t’ from ‘double’
g++ -shared -L/usr/local/lib64 -o ashr.so MixEM.o RcppExports.o -L/data/tools/R-3.1.1/lib64/R/lib -lR
installing to /mnt/lustre/home/mstephens/R/x86_64-unknown-linux-gnu-library/3.1/ashr/libs
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (ashr)

**Comment by ttriche** [comment]
Confirmed, it works now.  Cheers.
