### ISSUE TITLE
if df too big, my_etrunct throws warning

### ISSUE THREAD

**Issue by stephens999** [stephens999/ash#32]
this may mean posterior means are unreliable in that case?
maybe could fix by using log_gamma function, or replacing etrunct with etruncnorm

**Comment by daichaoxing** [comment]
If we replace gamma with lgamma, when df is too (my_etrunct(-1,2,2000)), it  does not throw a warning, instead, it throws a NaN, since log(G)=7596.384, G=Inf in R, while (A^(-(v-1)/2)-B^(-(v-1)/2)). We will by multiplying Inf by 0.

**Comment by daichaoxing** [comment]
I have rewritten the function and now it works fine in every situation

**Comment by daichaoxing** [comment]
lgamma is used instead, and when df is really too big, it would switch to my_etruncnorm() automatically.

**Comment by daichaoxing** [comment]
my_etrunct= function(a,b,v){
  if(a==b){
  	tmp=a
  }else{
  	A = v+a^2
 	B = v+b^2
  	F_a = pt(a,df=v)
  	F_b = pt(b,df=v)
  	lG=lgamma((v-1)/2)+(v/2)*log(v)-log(2*(F_b-F_a))-lgamma(v/2)-lgamma(1/2)
 	G=exp(lG)
 	ABpart=(A^(-(v-1)/2)-B^(-(v-1)/2))
  	if(G==Inf && ABpart==0){
  		#Use normal approximation instead
  		tmp=my_etruncnorm(a,b)
  	}else{
  		tmp=G*ABpart
  	}
  } 
  return(tmp)
}

**Comment by daichaoxing** [comment]
Would push to Github once it passed the R CMD check on my machine

**Comment by stephens999** [comment]
great!
thanks!
Matthew
